"""Central configuration for the AI News Agent (Routines edition).

Slimmer than v1's config.py: no agent-loop caps, no budget config, no
in-process scheduler config. Cron lives inside `routines/daily.yaml`,
token quota lives on the Max plan dashboard, and tools are configured
per-routine in YAML rather than enforced by a Python tool registry.

What stays:
    - File path constants for any local read/write the dashboard does
    - Routine IDs (filled by Phase R1)
    - Logging knob

Secrets stay in .env, loaded via python-dotenv at process start.
"""

import os
from pathlib import Path

VERSION = "0.1.0"

# ---------------------------------------------------------------------------
# Paths
# ---------------------------------------------------------------------------
# Local data/ is dev-only scratch. The primary store is the GitHub data
# branch (see SPEC.md / docs/routines-version-plan.md §3).
PROJECT_ROOT = Path(__file__).resolve().parent
DATA_DIR = PROJECT_ROOT / "data"
PROMPTS_DIR = PROJECT_ROOT / "prompts"
ROUTINES_DIR = PROJECT_ROOT / "routines"

# Dashboard-side caches kept locally even with data branch as primary.
# These are user-state files the dashboard writes between routine runs;
# they are not generated by the agent.
DASHBOARD_STATE_FILE = DATA_DIR / "dashboard_state.json"
SAVED_ITEMS_FILE = DATA_DIR / "saved_items.json"
PROFILE_FILE = DATA_DIR / "profile.md"

# ---------------------------------------------------------------------------
# Routines (Phase R1 fills the IDs)
# ---------------------------------------------------------------------------
ROUTINE_DAILY_ID = os.getenv("ROUTINE_DAILY_ID", "")
ROUTINE_FOLLOWUP_ID = os.getenv("ROUTINE_FOLLOWUP_ID", "")
ROUTINE_CUSTOM_ID = os.getenv("ROUTINE_CUSTOM_ID", "")
ROUTINE_API_TOKEN = os.getenv("ROUTINE_API_TOKEN", "")

# Per Routines docs (TODO: confirm exact base URL in R1).
ROUTINE_API_BASE = os.getenv(
    "ROUTINE_API_BASE",
    "https://api.claude.com/v1/routines",
)

# Default timeout for an HTTP-triggered Routine run. Daily and custom
# routines may take several minutes; follow-up should be faster.
ROUTINE_HTTP_TIMEOUT_SECONDS = int(os.getenv("ROUTINE_HTTP_TIMEOUT_SECONDS", "300"))

# ---------------------------------------------------------------------------
# GitHub data branch (Phase R6 dashboard refactor)
# ---------------------------------------------------------------------------
GITHUB_REPO_SLUG = os.getenv("GITHUB_REPO_SLUG", "emstacho-su/ai-news-agent-routines")
GITHUB_DATA_BRANCH = os.getenv("GITHUB_DATA_BRANCH", "data")
GITHUB_PAT = os.getenv("GITHUB_PAT", "")  # only needed if repo is private

# ---------------------------------------------------------------------------
# Dashboard
# ---------------------------------------------------------------------------
DASHBOARD_BASE_URL = os.getenv("DASHBOARD_BASE_URL", "http://localhost:8000")
DASHBOARD_PASSWORD = os.getenv("DASHBOARD_PASSWORD", "")

# ---------------------------------------------------------------------------
# Logging
# ---------------------------------------------------------------------------
VERBOSE_LOGGING = os.getenv("VERBOSE_LOGGING", "1") == "1"
